[package]
name = "unforgettable"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Is a pointee's destructor guaranteed to be run?"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psm = "0.1.21"